In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = {'Income': [25000, 27000, 30000, 32000, 50000, 120000, 250000]}
df = pd.DataFrame(data)

In [3]:
df

   Income
0   25000
1   27000
2   30000
3   32000
4   50000
5  120000
6  250000

In [4]:
df.skew()

Income    1.943067
dtype: float64

In [5]:
df['Income Log']=np.log1p(df['Income'])

In [6]:
df

   Income  Income Log
0   25000   10.126671
1   27000   10.203629
2   30000   10.308986
3   32000   10.373522
4   50000   10.819798
5  120000   11.695255
6  250000   12.429220

In [7]:
df['Income Log'].skew()

np.float64(1.2277500624230397)

In [8]:
df['Square root']=np.sqrt(df['Income'])

In [9]:
df

   Income  Income Log  Square root
0   25000   10.126671   158.113883
1   27000   10.203629   164.316767
2   30000   10.308986   173.205081
3   32000   10.373522   178.885438
4   50000   10.819798   223.606798
5  120000   11.695255   346.410162
6  250000   12.429220   500.000000

In [10]:
df['Square root'].skew()

np.float64(1.5927821188097289)

In [11]:
from sklearn.preprocessing import PowerTransformer

In [12]:
pt= PowerTransformer(method= 'yeo-johnson')

In [13]:
pt

PowerTransformer()

In [14]:
df['transformed income']=pt.fit_transform(df[['Income']])

In [15]:
df['transformed income'].skew()

np.float64(0.6079091790827778)

In [16]:
df = pd.DataFrame({'Quality': ['Low', 'Medium', 'High', 'Medium', 'Low']})

In [17]:
#Label encoding, used only for target variables (ordinal columns that contains boolean values (s/no or true/false))
#one hot encoding , used for all other columns by creating dummy columns .Add dummy colunmns for unique columns

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le= LabelEncoder()

In [20]:
df

  Quality
0     Low
1  Medium
2    High
3  Medium
4     Low

In [21]:
df['Encoded Quality']=le.fit_transform(df[['Quality']])

C:\Users\netha\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [22]:
df = pd.DataFrame({'Color': ['Red', 'Blue', 'Green', 'Red']})

In [23]:
df

   Color
0    Red
1   Blue
2  Green
3    Red

In [24]:
df_encoded = pd.get_dummies(df, columns=['Color'], drop_first=False)

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
ohe=OneHotEncoder(sparse_output=False)

In [27]:
encoded=ohe.fit_transform(df[['Color']])

In [28]:
encoded_df = pd.DataFrame(encoded, columns=ohe.get_feature_names_out(['Color']))

In [29]:
#feature Selection f_regressor

In [30]:
from sklearn.feature_selection import SelectKBest ,f_classif

In [31]:
from sklearn.datasets import load_iris

In [32]:
iris = load_iris()
X = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

In [33]:
selector=SelectKBest(score_func=f_classif,k=2)
xnew=selector.fit_transform(X,y)

In [34]:
selectorfeatures=X.columns[selector.get_support()]

In [35]:
selectorfeatures

Index(['petal length (cm)', 'petal width (cm)'], dtype='object')

In [36]:
#scaling
#standard scaler(0-1)
#min max scaler

In [37]:
#smote technique should be made before feature selection to make the data balanced
#over sampling - increase the row size
#under Sampling - decrease the row size

Classification is a supervised machine learning technique used to predict a categorical class label. The model learns from labeled data and classifies new data points into one of the predefined categories.
Types of Classification:
Binary Classification: Only two possible classes (e.g., 0 or 1)
Multi-class Classification: More than two classes (e.g., classify animals as Cat, Dog, or Bird)
Multi-label Classification: Each sample can belong to more than one class

#accuracy,precision ,f1 score ,recall ,confusion matrix

Naive Bayes Gaussian NB

Naive Bayes is a probabilistic classifier based on Bayes' Theorem. It assumes that features are independent of each other given the class label (this is the "naive" assumption).
variant Use Case Description
GaussianNB Continuous features Assumes normal distribution
MultinomialNB Text data, word counts Works with frequencies
BernoulliNB Binary features Presence or absence of features

Accuracy
Definition:
Accuracy is the ratio of correct predictions (both true positives and true negatives) to the total number of predictions.
Accuracy=𝑇𝑃+𝑇𝑁/ 𝑇𝑃+𝑇𝑁+𝐹𝑃+𝐹𝑁

Accuracy= 
TotalNumberofPredictions/NumberofCorrectPredictions

Precision= TP+FP /TP
TP = True Positives
FP = False Positives

Recall= TP+FN/TP
F1 Score=2× (Precision+Recall/Precision×Recall)